#version: "3.6"

# Using Docker_BuildKit which requires:
# export DOCKER_BUILDKIT=1
# export COMPOSE_DOCKER_CLI_BUILD=1

x-build-args:
  &build_args
  INSTALL_PYTHON_VERSION: 3.9

services:
  # https://milvus.io/docs/install_standalone-docker-compose-gpu.md
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./milvus/etcd:/etcd
    networks:
      - backend
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./milvus/minio:/minio_data
    networks:
      - backend
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    hostname: milvus-host
    image: milvusdb/milvus:v2.4.13-gpu
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      #- ./milvus.yaml:/milvus/configs/milvus.yaml
      - ./milvus/milvus:/var/lib/milvus
    networks:
      - backend
    ports:
      - "19530:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    depends_on:
      - "etcd"
      - "minio"
  
  api:
    restart: always
    build: 
      context: ./rag_api
      dockerfile: jupyter.dockerfile  
    image: deh_rag_api
    container_name: deh_rag_api
    hostname: deh
    ports:
      - "8080:8080"
    volumes:
      - data-vol:/data
      - "./rag_api:/app"  # Dev setting
      - ./rag_api/notebooks:/home/jovyan/work
    environment:
      - LLM_MODEL_NAME=llm_model
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      ollama:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - frontend
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # https://github.com/valiantlynx/ollama-docker
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: missing
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_DEBUG=1
      - OLLAMA_FLASH_ATTENTION=1  # Enable flash attention
      - OLLAMA_TIMEOUT=90  # Set timeout to 1 minute and 30 seconds
      - OLLAMA_LLM_LIBRARY="cuda_v12" # Use CUDA for LLM
      - OLLAMA_MAX_LOADED_MODELS=16
      - OLLAMA_LOAD_TIMEOUT:480
      - OLLAMA_NUM_PARALLEL=32
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# Network Definitions
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# Storage Volumes
volumes:
  secret-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./secrets
  data-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  db-vol: null
  milvus-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./milvus