name: Code Quality Check

on:
  workflow_dispatch:
  pull_request_target:  # will always use the workflow definition from master/main, not your PR!
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]
    branches:
      - main


jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Enable Python
      - name: Enable Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'

      # Check Markdown
      - name: Lint all Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: '.github/workflows/config/markdownlint.yml'
          globs: '**/*.md'
        continue-on-error: true

      # Install Linting dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Linters
      - name: Lint with flake8
        run: |
          flake8 measurement/src
          flake8 rag_api/src
          flake8 ui/deh

      # TODO
      # - Unit test run
