name: CIRI Front End Build

on:
  push:
    branches:
      - master

jobs:
  buildContainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          set -e
          docker build -t ciri_frontend:latest .
          docker tag ciri_frontend:latest \
                      ghcr.io/${{ github.repository }}/ciri_frontend:latest

      - name: Push Container Image
        run: |
          set -e
          docker push ghcr.io/${{ github.repository }}/ciri_frontend:latest